server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: duyo-api
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:6875/materialize
    username: materialize
    password:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20
  jpa:
    database: POSTGRESQL
    show-sql: true
## Logging properties
logging:
  level:
    root: INFO
    io:
      debezium:
        mysql:
          BinlogReader: INFO
    com:
      baeldung:
        libraries:
          debezium: DEBUG